import sys
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
# --------------------------------------------------------------

import streamlit as st
import pandas as pd
import shutil
import plotly.graph_objects as go

from src.config import RunConfig, ARTIFACT_DIR
from src.storage import load_df, load_json
from src import chatbot

# Lazy import to avoid circular/import timing issues
FinancePipeline = None
def _get_pipeline():
    global FinancePipeline
    if FinancePipeline is None:
        from src.pipeline import FinancePipeline as FP
        FinancePipeline = FP
    return FinancePipeline

st.set_page_config(page_title="Finance OOP ETL", layout="wide")
st.title("Finance Analysis (OOP + ETL)")

# ---------------- Sidebar inputs ----------------
with st.sidebar:
    tickers = st.text_input("Tickers (comma-separated)", "AAPL,MSFT,GOOGL")
    start = st.date_input("Start", value=pd.to_datetime("2018-01-01")).strftime("%Y-%m-%d")
    end = st.date_input("End", value=pd.Timestamp.today()).strftime("%Y-%m-%d")
    invest = st.number_input("Investment Amount", min_value=100.0, value=15000.0, step=100.0)
    cache_key = st.text_input("Run name (cache key)", "demo")

# Small helper to render the nice view for a given artifact key
def render_results_for_key(key: str, show_paths: dict | None = None):
    run_root = ARTIFACT_DIR / key
    summary_path = run_root / "summary.json"
    if not summary_path.exists():
        st.info(f"No artifacts found yet for key '{key}'. Run the pipeline first.")
        return

    summary = load_json(summary_path)

    st.subheader("Portfolio Optimization Results")
    c1, c2, c3 = st.columns(3)
    c1.metric("Expected Return", f"{summary.get('exp_return', 0):.2%}")
    c2.metric("Volatility", f"{summary.get('volatility', 0):.2%}")
    c3.metric("Sharpe Ratio", f"{summary.get('sharpe', 0):.2f}")

    if summary.get("weights"):
        st.write("Weights")
        weights_df = pd.DataFrame(list(summary["weights"].items()), columns=["Ticker", "Weight"])
        st.dataframe(weights_df, use_container_width=True)

    if summary.get("discrete_allocation"):
        st.write("Discrete Allocation")
        alloc_df = pd.DataFrame(list(summary["discrete_allocation"].items()), columns=["Ticker", "Shares"])
        st.dataframe(alloc_df, use_container_width=True)

    failed = summary.get("failed_tickers", [])
    if failed:
        st.warning(f"Skipped {len(failed)} ticker(s): {', '.join(failed)}")

    # --- Price History (rebuild from CSV with Plotly) ---
    close_path = run_root / "close.csv"
    if close_path.exists():
        close_df = load_df(close_path)
        if not close_df.empty:
            fig = go.Figure()
            for col in close_df.columns:
                fig.add_trace(go.Scatter(x=close_df.index, y=close_df[col], mode="lines", name=col))
            fig.update_layout(
                title="Stock Price History",
                xaxis_title="Date",
                yaxis_title="Price",
                template="plotly_white",
                paper_bgcolor="white",
                plot_bgcolor="white",
            )
            st.subheader("Price History")
            st.plotly_chart(fig, use_container_width=True)

    # --- Predicted vs Actual (rebuild from CSV with Plotly) ---
    preds_path = run_root / "ml_predictions.csv"
    if preds_path.exists():
        preds_df = load_df(preds_path)
        if not preds_df.empty and {"Return", "Predictions"}.issubset(preds_df.columns):
            fig = go.Figure()
            fig.add_trace(go.Scatter(x=preds_df.index, y=preds_df["Return"], mode="lines", name="Actual"))
            fig.add_trace(go.Scatter(x=preds_df.index, y=preds_df["Predictions"], mode="lines", name="Predicted"))
            fig.update_layout(
                title="Predicted vs Actual Returns",
                xaxis_title="Date",
                yaxis_title="Return",
                template="plotly_white",
                paper_bgcolor="white",
                plot_bgcolor="white",
            )
            st.subheader("Predicted vs Actual Returns")
            st.plotly_chart(fig, use_container_width=True)

    # --- Static images generated by the pipeline (Matplotlib) ---
    ret_dist_png = run_root / "return_distribution.png"
    if ret_dist_png.exists():
        st.subheader("Return Distribution")
        st.image(str(ret_dist_png), use_column_width=True)

    alloc_cmp_png = run_root / "allocation_comparison.png"
    if alloc_cmp_png.exists():
        st.subheader("Allocation Comparison")
        st.image(str(alloc_cmp_png), use_column_width=True)

    # --- Optional: neatly show artifact paths (collapsed) ---
    if show_paths:
        with st.expander("Show artifact paths"):
            for k, v in show_paths.items():
                st.code(f"{k}: {v}")

# ---------------- Run pipeline ----------------
if st.button("Run Pipeline"):
    cfg = RunConfig(
        tickers=[t.strip() for t in tickers.split(",") if t.strip()],
        start=start,
        end=end,
        investment_amount=float(invest),
        cache_key=cache_key,
    )
    try:
        FP = _get_pipeline()
        paths = FP(cfg).run()
        st.success("Done. Artifacts saved.")
        render_results_for_key(cache_key, show_paths=paths)
    except Exception as e:
        st.error(str(e))
        st.info("Tips: try fewer tickers, a shorter range (e.g., 2018–today), or wait 1–2 minutes to avoid Yahoo rate limits.")

st.markdown("---")

# ---------------- Load Results (manual) ----------------
st.header("Load Results")
key = st.text_input("Artifact key to load", "demo")
if st.button("Load"):
    render_results_for_key(key)

st.markdown("---")

# ---------------- Optional: manage artifacts from UI ----------------
with st.expander("Manage Artifacts (optional)"):
    # list existing keys
    keys = sorted([p.name for p in (ARTIFACT_DIR.glob("*")) if p.is_dir()])
    if keys:
        st.caption("Existing keys:")
        st.write(", ".join(keys))
    del_key = st.text_input("Delete cache key", "")
    if st.button("Delete"):
        if del_key:
            target = ARTIFACT_DIR / del_key
            if target.exists():
                shutil.rmtree(target)
                st.success(f"Deleted artifacts for key '{del_key}'.")
            else:
                st.info(f"No artifacts found for key '{del_key}'.")
        else:
            st.info("Enter a key to delete.")

st.markdown("---")

# ---------------- Finance chatbot ----------------
st.header("Finance Chatbot")
st.caption("Ask about a finance term, or about the results of a saved run (for example: What is my Sharpe ratio?).")
chat_key = st.text_input("Run to chat about", cache_key, key="chat_key")


@st.cache_resource(show_spinner="Loading the language model (first question only)...")
def _qa_model():
    return chatbot.get_qa_model()


_summary_path = ARTIFACT_DIR / chat_key / "summary.json"
_summary = load_json(_summary_path) if _summary_path.exists() else None

# Reload saved history when the app starts or the run changes
if st.session_state.get("chat_loaded_for") != chat_key:
    st.session_state["chat"] = chatbot.load_history(chat_key)
    st.session_state["chat_loaded_for"] = chat_key


def _show(msg: dict):
    with st.chat_message(msg["role"]):
        st.write(msg["content"])
        if msg.get("latency_ms") is not None:
            st.caption(f"Answered in {msg['latency_ms'] / 1000:.2f} s")


for _m in st.session_state["chat"]:
    _show(_m)

_q = st.chat_input("Ask a finance question")
if _q:
    _prev = next((m["content"] for m in reversed(st.session_state["chat"]) if m["role"] == "user"), None)
    _user = {"role": "user", "content": _q}
    _show(_user)
    _res = chatbot.answer(_q, summary=_summary, qa=_qa_model(), previous_question=_prev)
    _bot = {"role": "assistant", "content": _res["answer"], "latency_ms": _res["latency_ms"]}
    _show(_bot)
    st.session_state["chat"] += [_user, _bot]
    chatbot.save_history(chat_key, st.session_state["chat"])

if st.session_state["chat"] and st.button("Clear chat history"):
    st.session_state["chat"] = []
    chatbot.save_history(chat_key, [])
    st.rerun()
